script: "bundle exec rake travis"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.9.2
notifications:
  email:
    - didier@nocoffee.fr
    - mario@mariovisic.com
  irc: "irc.freenode.org#locomotivecms"
